### ISSUE TITLE
Research : How is data getting into redshift?

### ISSUE THREAD

**Issue by twentymurial33** [twentymurial33/dashboard#10]
Find out how data is currently being ingested by Redshift, currently DWH used for the different data sources

**Comment by twentymurial33** [comment]
https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/build-an-etl-service-pipeline-to-load-data-incrementally-from-amazon-s3-to-amazon-redshift-using-aws-glue.html

**Comment by brentmclark** [comment]
Do you think it's safe to separate "dashboard data" from "application data" at this point?

**Comment by twentymurial33** [comment]
Yes, the application data will come from the 2nd Data Source( S3,Json Placeholder OR DynamoDB) and Dashboard Data will come from Redshift

**Comment by brentmclark** [comment]
That being the case, it may not matter how data gets into redshift at this point.

"It comes from an ETL process" is probably good enough.
