### ISSUE TITLE
Embedded new url from API but still getting Unauthorized error(403)

### ISSUE THREAD

**Issue by brentmclark** [twentymurial33/dashboard#21]
I can't whitelist the http- url for testing so very confused :(

See #20 for related code

**Comment by twentymurial33** [comment]
I was trying to see if I can whitelist the dev -`http://localhost:3000` but I get the same error even in PROD

**Comment by brentmclark** [comment]
Since they only want the domain, have you tried `http://localhost` (without the port) instead?

**Comment by twentymurial33** [comment]
Just tried that and error message is `This Domain is not supported. QuickSight dashboards can only be embedded in valid https domains.`

**Comment by twentymurial33** [comment]
<img width="949" alt="Screen Shot 2022-07-06 at 5 22 18 PM" src="https://user-images.githubusercontent.com/34128735/177645820-37d8fd62-2b69-46da-b062-b6c2ad79a1e1.png">

**Comment by brentmclark** [comment]
I _think_ I understand what's happening here.  The [documentation you linked](https://docs.aws.amazon.com/quicksight/latest/user/embedding-run-time.html) is for embedding URLs *at runtime*, not statically (i.e. through the UI).  I think you need to follow the instructions on generated the runtime URL embeds, which involves JavaScript code.

**Comment by twentymurial33** [comment]
Ok following the documentation ...added the `getEmbedUrl.js` in the code `Node.js`

**Comment by twentymurial33** [comment]
Opened AWS Ticket for troubleshooting cc @brentmclark
